services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env #use .env file for PUID and PGID values
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev, #Put your IP here it is a requirement https://github.com/gethomepage/homepage/blob/dev/docs/installation/index.md#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID


